In [57]:
import pandas as pd
df = pd.read_csv(r'C:\Users\litni\OneDrive\Documents\anki\scraping\extracted_text_simple\extracted_text_20260220_221451.csv')

In [58]:
df.head(10)

,filename,cwas_number,date,text,confidence,language,psm_mode,preprocessing_variant,combined_score,processing_time,file_size,dimensions,character_count,timestamp,is_coined
0,CWAS_0005_2026-02-10.jpg,5.0,2026-02-10,Etymology It is a loan word from Iranian sourc...,93.529412,eng+hye,6,2,0.880588,18.506572,136982,2048x2048,119,2026-02-20T21:27:08.654436,no
1,CWAS_0001_2026-02-14.jpg,1.0,2026-02-14,Example Կործանումը անխուսափելի En: The destruc...,94.437500,eng+hye,6,2,0.883312,18.857620,140631,2048x2048,137,2026-02-20T21:27:08.995698,no
2,CWAS_0011_2026-02-06.jpg,11.0,2026-02-06,"Etymology It derives from ""կաթլակ"" (small drop...",92.368421,eng+hye,6,1,0.927105,19.210064,147045,2048x2048,141,2026-02-20T21:27:09.360003,no
3,CWAS_0014_2026-02-06.jpg,14.0,2026-02-06,"Word breakdown ատ + ել ""Ատ"" derives from Indo-...",95.068966,eng+hye,6,3,0.935207,19.403209,159046,2048x2048,186,2026-02-20T21:27:09.555154,no
4,CWAS_0007_2026-02-14.jpg,7.0,2026-02-14,"Example bret ինծի նուէր պիտի գնես, օգտակար բան...",92.655172,eng+hye,6,3,0.877966,19.786663,149842,2048x2048,180,2026-02-20T21:27:09.936602,no
5,CWAS_0008_2026-02-08.jpg,8.0,2026-02-08,"Word breakdown օգտ + w+ կար ""Օգտ"" derives from...",90.843750,eng+hye,11,6,0.922531,20.179885,167848,2048x2048,205,2026-02-20T21:27:10.329823,no
6,CWAS_0002_2026-02-13.jpg,2.0,2026-02-13,"Word breakdown ան + խուսափ + ելի ""Ան"" is a neg...",91.714286,eng+hye,6,0,0.925143,20.825547,166068,2048x2048,214,2026-02-20T21:27:10.973410,no
7,CWAS_0016_2026-02-04.jpg,16.0,2026-02-04,Declension Singular Plural Վարդ Վարդեր Վարդի Վ...,92.218750,eng+hye,6,4,0.876656,21.456307,169403,2048x2048,221,2026-02-20T21:27:11.608251,no
8,CWAS_0018_2026-02-03.jpg,18.0,2026-02-03,"""Հ Centre for Western Armenian Studies Արեւմտա...",94.613636,eng+hye,6,6,0.933841,21.901448,179665,2048x2048,273,2026-02-20T21:27:12.053392,no
9,CWAS_0015_2026-02-05.jpg,15.0,2026-02-05,Centre for Western Armenian Studies Արեւմտահայ...,94.888889,eng+hye,6,0,0.934667,22.096496,181639,2048x2048,283,2026-02-20T21:27:12.248440,no

In [ ]:
# Remove the copyright notice from extracted text
copyright_text = "The «Word of the Day» is the intellectual property of the Centre for Western Armenian Studies, and any use of it on other platforms or in any other circumstances requires the permission of the Centre."
copyright_text = "Word breakdown օգտ + w+ կար "Օգտ" derives from "օգուտ" (usefulness, benefit) "Կար" is the root of (possible). "Ա" Տ a linking letter. Centre for Western Armenian Studies @ Արեւմտահայագիտական ՈւսմաԿց Կեդրոն"
title_text = "Centre for Western Armenian Studies Արեւմտահայագիտական Ուսմանց Կեդրոն"
add_text = "Centre for Western Armenian Studies | Արեւմտահայագիտական Ուսմանց Կեդրոն WESTERN ARMENIAN"
# Clean the text column
df['text'] = df['text'].str.replace(copyright_text, '', regex=False)
df['text'] = df['text'].str.replace(title_text, '', regex=False)

# Also remove any extra whitespace that might be left
df['text'] = df['text'].str.strip()

print(f"Cleaned text in {len(df)} rows")
print("\nFirst few cleaned entries:")
df.head()

Cleaned text in 2211 rows

First few cleaned entries:

,filename,cwas_number,date,text,confidence,language,psm_mode,preprocessing_variant,combined_score,processing_time,file_size,dimensions,character_count,timestamp,is_coined
0,CWAS_0005_2026-02-10.jpg,5.0,2026-02-10,Etymology It is a loan word from Iranian sources.,93.529412,eng+hye,6,2,0.880588,18.506572,136982,2048x2048,119,2026-02-20T21:27:08.654436,no
1,CWAS_0001_2026-02-14.jpg,1.0,2026-02-14,Example Կործանումը անխուսափելի En: The destruc...,94.437500,eng+hye,6,2,0.883312,18.857620,140631,2048x2048,137,2026-02-20T21:27:08.995698,no
2,CWAS_0011_2026-02-06.jpg,11.0,2026-02-06,"Etymology It derives from ""կաթլակ"" (small drop...",92.368421,eng+hye,6,1,0.927105,19.210064,147045,2048x2048,141,2026-02-20T21:27:09.360003,no
3,CWAS_0014_2026-02-06.jpg,14.0,2026-02-06,"Word breakdown ատ + ել ""Ատ"" derives from Indo-...",95.068966,eng+hye,6,3,0.935207,19.403209,159046,2048x2048,186,2026-02-20T21:27:09.555154,no
4,CWAS_0007_2026-02-14.jpg,7.0,2026-02-14,"Example bret ինծի նուէր պիտի գնես, օգտակար բան...",92.655172,eng+hye,6,3,0.877966,19.786663,149842,2048x2048,180,2026-02-20T21:27:09.936602,no

In [60]:
# Add category column based on text content
def categorize_text(text):
    text_lower = str(text).lower()
    
    if add_text.lower() in text_lower:
        return 'Add'
    elif "Vocabulary Enhancement Course".lower() in text_lower:
        return 'Add'
    elif 'etymology' in text_lower:
        return 'Etymology'
    elif 'word breakdown' in text_lower:
        return 'Word Breakdown'
    elif 'phrasal breakdown' in text_lower:
        return 'Phrasal Breakdown'
    elif 'declension' in text_lower and 'example' in text_lower:
        return 'Declension-Example'
    elif 'example' in text_lower:
        return 'Example'
    elif 'declension' in text_lower:
        return 'Declension'
    elif 'conjunction' in text_lower:
        return 'Conjunction'
    elif 'conjugation' in text_lower:
        return 'Conjugation'
    elif 'present tense & immediate present tense' in text_lower:
        return "Conjunction"
    else:
        return 'Other'

# Apply categorization
df['category'] = df['text'].apply(categorize_text)

# Show category distribution
print("Category distribution:")
print(df['category'].value_counts())
print(f"\nTotal entries: {len(df)}")

# Show a few examples of each category
print("\nSample entries by category:")
for category in df['category'].unique():
    print(f"\n--- {category} ---")
    sample = df[df['category'] == category].head(2)
    for idx, row in sample.iterrows():
        print(f"Text preview: {str(row['text'])[:100]}...")

Category distribution:
category
Other                 849
Declension-Example    483
Word Breakdown        414
Etymology             206
Example               178
Add                    56
Conjugation            13
Phrasal Breakdown       8
Declension              4
Name: count, dtype: int64

Total entries: 2211

Sample entries by category:

--- Etymology ---
Text preview: Etymology It is a loan word from Iranian sources....
Text preview: Etymology It derives from "կաթլակ" (small drop), the diminutive form of...

--- Example ---
Text preview: Example Կործանումը անխուսափելի En: The destruction was unavoidable....
Text preview: Example bret ինծի նուէր պիտի գնես, օգտակար բաներ ա՛ռ: If you are going to buy me a gift, buy somethi...

--- Word Breakdown ---
Text preview: Word breakdown ատ + ել "Ատ" derives from Indo-European sources. "Ել" is the verb ending of the first...
Text preview: Word breakdown օգտ + w+ կար "Օգտ" derives from "օգուտ" (usefulness, benefit) "Կար" is the root of (p...

--- Declension-Example ---
Text preview: Declension Singular Plural Վարդ Վարդեր Վարդի Վարդերու ՎարդԷէ ՎարդերԷ Վարդով Վարդերով Example Վարդի ո...
Text preview: Declension Singular Plural Կայլակ Կայլակներ Կայլակի Կայլակներու Կայլակէ ԿայլակներԷ Կայլակով Կայլակնե...

--- Other ---
Text preview: "Հ...
Text preview: a-del (Verb)...

--- Add ---
Text preview: թ * : Ն Հ» «2 լ Ն) ՖԵԻՒՍՉ - Sign up to our Vocabulary Enhancement Course Part starting in January 20...
Text preview: թ * : Ն Հ» «2 լ Ն) ՖԵԻՒՍՉ - Sign up to our Vocabulary Enhancement Course Part starting in January 20...

--- Conjugation ---
Text preview: Conjugation Present tense & Present tense negation & Past tense (negation) Immediate present tense I...
Text preview: Conjugation Present tense & Present Present tense negation & Past tense (negation) tense continuous ...

--- Declension ---
Text preview: Declension Singular Plural Դաշտ Դաշտեր Դաշտի Դաշտերու ԴաշտԷ ԴաշտերԷ Դաշտով Centre for Western Armeni...
Text preview: Declension Singular Plural ՈսկԵեխոյզ Ոսկեխոյզեր Ոսկեխոյզի ՈԿկԵխոյզերու Ոսկեխոյզէ ՈսկեխոյզերԷ Ոսկեխոյ...

--- Phrasal Breakdown ---
Text preview: Phrasal breakdown Դպր + աց / դաս "Դպրաօգ" is the genitive plural of "դպիր" (acolyte) in Krapar. "Դաս...
Text preview: Phrasal breakdown վարձկան + գրիչ "Վարձկան" means "mercenary". "Գրիչ" means "pen"....

In [61]:
df.head(20)

,filename,cwas_number,date,text,confidence,language,psm_mode,preprocessing_variant,combined_score,processing_time,file_size,dimensions,character_count,timestamp,is_coined,category
0,CWAS_0005_2026-02-10.jpg,5.0,2026-02-10,Etymology It is a loan word from Iranian sources.,93.529412,eng+hye,6,2,0.880588,18.506572,136982,2048x2048,119,2026-02-20T21:27:08.654436,no,Etymology
1,CWAS_0001_2026-02-14.jpg,1.0,2026-02-14,Example Կործանումը անխուսափելի En: The destruc...,94.437500,eng+hye,6,2,0.883312,18.857620,140631,2048x2048,137,2026-02-20T21:27:08.995698,no,Example
2,CWAS_0011_2026-02-06.jpg,11.0,2026-02-06,"Etymology It derives from ""կաթլակ"" (small drop...",92.368421,eng+hye,6,1,0.927105,19.210064,147045,2048x2048,141,2026-02-20T21:27:09.360003,no,Etymology
3,CWAS_0014_2026-02-06.jpg,14.0,2026-02-06,"Word breakdown ատ + ել ""Ատ"" derives from Indo-...",95.068966,eng+hye,6,3,0.935207,19.403209,159046,2048x2048,186,2026-02-20T21:27:09.555154,no,Word Breakdown
4,CWAS_0007_2026-02-14.jpg,7.0,2026-02-14,"Example bret ինծի նուէր պիտի գնես, օգտակար բան...",92.655172,eng+hye,6,3,0.877966,19.786663,149842,2048x2048,180,2026-02-20T21:27:09.936602,no,Example
5,CWAS_0008_2026-02-08.jpg,8.0,2026-02-08,"Word breakdown օգտ + w+ կար ""Օգտ"" derives from...",90.843750,eng+hye,11,6,0.922531,20.179885,167848,2048x2048,205,2026-02-20T21:27:10.329823,no,Word Breakdown
6,CWAS_0002_2026-02-13.jpg,2.0,2026-02-13,"Word breakdown ան + խուսափ + ելի ""Ան"" is a neg...",91.714286,eng+hye,6,0,0.925143,20.825547,166068,2048x2048,214,2026-02-20T21:27:10.973410,no,Word Breakdown
7,CWAS_0016_2026-02-04.jpg,16.0,2026-02-04,Declension Singular Plural Վարդ Վարդեր Վարդի Վ...,92.218750,eng+hye,6,4,0.876656,21.456307,169403,2048x2048,221,2026-02-20T21:27:11.608251,no,Declension-Example
8,CWAS_0018_2026-02-03.jpg,18.0,2026-02-03,"""Հ",94.613636,eng+hye,6,6,0.933841,21.901448,179665,2048x2048,273,2026-02-20T21:27:12.053392,no,Other
9,CWAS_0015_2026-02-05.jpg,15.0,2026-02-05,a-del (Verb),94.888889,eng+hye,6,0,0.934667,22.096496,181639,2048x2048,283,2026-02-20T21:27:12.248440,no,Other
10,CWAS_0003_2026-02-13.jpg,3.0,2026-02-13,an-khou-sa-pe-li (Adjective) Unavoidable,95.021739,eng+hye,11,0,0.935065,22.185910,207328,2048x2048,311,2026-02-20T21:27:12.333774,no,Other
11,CWAS_0012_2026-02-05.jpg,12.0,2026-02-05,Կայլակ gay-lag (Noun) Drop (formal),94.500000,eng+hye,11,0,0.933500,22.271197,189495,2048x2048,306,2026-02-20T21:27:12.421136,no,Other
12,CWAS_0010_2026-02-06.jpg,10.0,2026-02-06,Declension Singular Plural Կայլակ Կայլակներ Կա...,91.714286,eng+hye,6,2,0.875143,22.297390,178002,2048x2048,257,2026-02-20T21:27:12.447328,no,Declension-Example
13,CWAS_0009_2026-02-07.jpg,9.0,2026-02-07,"Օգտակար ok-da-gar Useful, beneficial",95.680851,eng+hye,11,4,0.937043,22.396484,201182,2048x2048,307,2026-02-20T21:27:12.546423,no,Other
14,CWAS_0021_2026-02-03.jpg,21.0,2026-02-03,Փակարան pa-ga-ran (Noun) Conclave,95.212766,eng+hye,11,0,0.935638,22.573271,195033,2048x2048,304,2026-02-20T21:27:12.725215,no,Other
15,CWAS_0006_2026-02-18.jpg,6.0,2026-02-18,"""Հ ALO o NID 2. Force",93.040816,eng+hye,6,6,0.929122,22.682230,189206,2048x2048,292,2026-02-20T21:27:12.830093,no,Other
16,CWAS_0004_2026-02-12.jpg,4.0,2026-02-12,Declension Singular Plural ՈւԺ Ուժեր ՈւԺի ՈւԺե...,91.563636,eng+hye,6,4,0.924691,24.411843,194482,2048x2048,334,2026-02-20T21:27:14.559706,no,Declension-Example
17,CWAS_0013_2026-02-19.jpg,13.0,2026-02-19,Conjugation Present tense & Present tense nega...,92.061728,eng+hye,11,0,0.926185,28.245167,272425,2048x2048,542,2026-02-20T21:27:18.397111,no,Example
18,CWAS_0022_2026-02-02.jpg,22.0,2026-02-02,Example Սաստիկ ձիւնը ձամբաներու փակումին պատճա...,90.260870,eng+hye,6,6,0.870783,19.775422,151272,2048x2048,171,2026-02-20T21:27:28.430857,no,Example
19,CWAS_0028_2026-02-02.jpg,28.0,2026-02-02,"Word breakdown թղթ + wi + խաղ ""Թղթ"" derives fr...",89.413793,eng+hye,11,4,0.918241,20.097656,158368,2048x2048,181,2026-02-20T21:27:29.459669,no,Word Breakdown

In [62]:
# Split Declension-Example rows using pandas operations
import re

# Create a function to extract text after "example"
def extract_after_example(text):
    """Extract text that comes after 'example' (case insensitive)"""
    if pd.isna(text) or text == '':
        return ''
    
    text_str = str(text)
    # Find "example" case insensitive
    match = re.search(r'\bexample\b', text_str, re.IGNORECASE)
    
    if match:
        return text_str[match.end():].strip()
    return ''

def extract_before_example(text):
    """Extract text that comes before 'example' (case insensitive)"""
    if pd.isna(text) or text == '':
        return text
    
    text_str = str(text)
    # Find "example" case insensitive
    match = re.search(r'\bexample\b', text_str, re.IGNORECASE)
    
    if match:
        return text_str[:match.start()].strip()
    return text_str

# Filter rows with "Declension-Example" category
declension_example_mask = df['category'] == 'Declension-Example'
print(f"Found {declension_example_mask.sum()} rows with 'Declension-Example' category")

if declension_example_mask.sum() > 0:
    # Create new rows for the "Example" part
    example_rows = df[declension_example_mask].copy()
    example_rows['category'] = 'Example'
    example_rows['text'] = example_rows['text'].apply(extract_after_example)
    
    # Update original rows to contain only the declension part
    df.loc[declension_example_mask, 'category'] = 'Declension'
    df.loc[declension_example_mask, 'text'] = df.loc[declension_example_mask, 'text'].apply(extract_before_example)
    
    # Concatenate the new example rows to the dataframe
    df = pd.concat([df, example_rows], ignore_index=True)
    
    print(f"✓ Split {declension_example_mask.sum()} rows")
    print(f"✓ Updated original rows to 'Declension' category")
    print(f"✓ Created {len(example_rows)} new 'Example' rows")
    print(f"✓ New total rows: {len(df)}")
    
    # Show sample results
    print("\nSample of updated rows:")
    declension_rows = df[df['category'] == 'Declension'].head(2)
    example_rows_sample = df[df['category'] == 'Example'].head(2)
    
    print("\nDeclension rows:")
    for idx, row in declension_rows.iterrows():
        print(f"Text: {str(row['text'])[:100]}...")
    
    print("\nExample rows:")
    for idx, row in example_rows_sample.iterrows():
        print(f"Text: {str(row['text'])[:100]}...")
    
else:
    print("No 'Declension-Example' rows found to split")

# Show updated category distribution
print(f"\nUpdated category distribution:")
print(df['category'].value_counts())

Found 483 rows with 'Declension-Example' category
✓ Split 483 rows
✓ Updated original rows to 'Declension' category
✓ Created 483 new 'Example' rows
✓ New total rows: 2694

Sample of updated rows:

Declension rows:
Text: Declension Singular Plural Վարդ Վարդեր Վարդի Վարդերու ՎարդԷէ ՎարդերԷ Վարդով Վարդերով...
Text: Declension Singular Plural Կայլակ Կայլակներ Կայլակի Կայլակներու Կայլակէ ԿայլակներԷ Կայլակով Կայլակնե...

Example rows:
Text: Example Կործանումը անխուսափելի En: The destruction was unavoidable....
Text: Example bret ինծի նուէր պիտի գնես, օգտակար բաներ ա՛ռ: If you are going to buy me a gift, buy somethi...

Updated category distribution:
category
Other                849
Example              661
Declension           487
Word Breakdown       414
Etymology            206
Add                   56
Conjugation           13
Phrasal Breakdown      8
Name: count, dtype: int64

In [64]:
df.head(20)

,filename,cwas_number,date,text,confidence,language,psm_mode,preprocessing_variant,combined_score,processing_time,file_size,dimensions,character_count,timestamp,is_coined,category
0,CWAS_0005_2026-02-10.jpg,5.0,2026-02-10,Etymology It is a loan word from Iranian sources.,93.529412,eng+hye,6,2,0.880588,18.506572,136982,2048x2048,119,2026-02-20T21:27:08.654436,no,Etymology
1,CWAS_0001_2026-02-14.jpg,1.0,2026-02-14,Example Կործանումը անխուսափելի En: The destruc...,94.437500,eng+hye,6,2,0.883312,18.857620,140631,2048x2048,137,2026-02-20T21:27:08.995698,no,Example
2,CWAS_0011_2026-02-06.jpg,11.0,2026-02-06,"Etymology It derives from ""կաթլակ"" (small drop...",92.368421,eng+hye,6,1,0.927105,19.210064,147045,2048x2048,141,2026-02-20T21:27:09.360003,no,Etymology
3,CWAS_0014_2026-02-06.jpg,14.0,2026-02-06,"Word breakdown ատ + ել ""Ատ"" derives from Indo-...",95.068966,eng+hye,6,3,0.935207,19.403209,159046,2048x2048,186,2026-02-20T21:27:09.555154,no,Word Breakdown
4,CWAS_0007_2026-02-14.jpg,7.0,2026-02-14,"Example bret ինծի նուէր պիտի գնես, օգտակար բան...",92.655172,eng+hye,6,3,0.877966,19.786663,149842,2048x2048,180,2026-02-20T21:27:09.936602,no,Example
5,CWAS_0008_2026-02-08.jpg,8.0,2026-02-08,"Word breakdown օգտ + w+ կար ""Օգտ"" derives from...",90.843750,eng+hye,11,6,0.922531,20.179885,167848,2048x2048,205,2026-02-20T21:27:10.329823,no,Word Breakdown
6,CWAS_0002_2026-02-13.jpg,2.0,2026-02-13,"Word breakdown ան + խուսափ + ելի ""Ան"" is a neg...",91.714286,eng+hye,6,0,0.925143,20.825547,166068,2048x2048,214,2026-02-20T21:27:10.973410,no,Word Breakdown
7,CWAS_0016_2026-02-04.jpg,16.0,2026-02-04,Declension Singular Plural Վարդ Վարդեր Վարդի Վ...,92.218750,eng+hye,6,4,0.876656,21.456307,169403,2048x2048,221,2026-02-20T21:27:11.608251,no,Declension
8,CWAS_0018_2026-02-03.jpg,18.0,2026-02-03,"""Հ",94.613636,eng+hye,6,6,0.933841,21.901448,179665,2048x2048,273,2026-02-20T21:27:12.053392,no,Other
9,CWAS_0015_2026-02-05.jpg,15.0,2026-02-05,a-del (Verb),94.888889,eng+hye,6,0,0.934667,22.096496,181639,2048x2048,283,2026-02-20T21:27:12.248440,no,Other
10,CWAS_0003_2026-02-13.jpg,3.0,2026-02-13,an-khou-sa-pe-li (Adjective) Unavoidable,95.021739,eng+hye,11,0,0.935065,22.185910,207328,2048x2048,311,2026-02-20T21:27:12.333774,no,Other
11,CWAS_0012_2026-02-05.jpg,12.0,2026-02-05,Կայլակ gay-lag (Noun) Drop (formal),94.500000,eng+hye,11,0,0.933500,22.271197,189495,2048x2048,306,2026-02-20T21:27:12.421136,no,Other
12,CWAS_0010_2026-02-06.jpg,10.0,2026-02-06,Declension Singular Plural Կայլակ Կայլակներ Կա...,91.714286,eng+hye,6,2,0.875143,22.297390,178002,2048x2048,257,2026-02-20T21:27:12.447328,no,Declension
13,CWAS_0009_2026-02-07.jpg,9.0,2026-02-07,"Օգտակար ok-da-gar Useful, beneficial",95.680851,eng+hye,11,4,0.937043,22.396484,201182,2048x2048,307,2026-02-20T21:27:12.546423,no,Other
14,CWAS_0021_2026-02-03.jpg,21.0,2026-02-03,Փակարան pa-ga-ran (Noun) Conclave,95.212766,eng+hye,11,0,0.935638,22.573271,195033,2048x2048,304,2026-02-20T21:27:12.725215,no,Other
15,CWAS_0006_2026-02-18.jpg,6.0,2026-02-18,"""Հ ALO o NID 2. Force",93.040816,eng+hye,6,6,0.929122,22.682230,189206,2048x2048,292,2026-02-20T21:27:12.830093,no,Other
16,CWAS_0004_2026-02-12.jpg,4.0,2026-02-12,Declension Singular Plural ՈւԺ Ուժեր ՈւԺի ՈւԺե...,91.563636,eng+hye,6,4,0.924691,24.411843,194482,2048x2048,334,2026-02-20T21:27:14.559706,no,Declension
17,CWAS_0013_2026-02-19.jpg,13.0,2026-02-19,Conjugation Present tense & Present tense nega...,92.061728,eng+hye,11,0,0.926185,28.245167,272425,2048x2048,542,2026-02-20T21:27:18.397111,no,Example
18,CWAS_0022_2026-02-02.jpg,22.0,2026-02-02,Example Սաստիկ ձիւնը ձամբաներու փակումին պատճա...,90.260870,eng+hye,6,6,0.870783,19.775422,151272,2048x2048,171,2026-02-20T21:27:28.430857,no,Example
19,CWAS_0028_2026-02-02.jpg,28.0,2026-02-02,"Word breakdown թղթ + wi + խաղ ""Թղթ"" derives fr...",89.413793,eng+hye,11,4,0.918241,20.097656,158368,2048x2048,181,2026-02-20T21:27:29.459669,no,Word Breakdown